name:                waveform-ana
version:             1.0.0.0
github:              "shotaizu/waveform-ana"
license:             GPL-3
author:              "Shota Izumiyama"
maintainer:          "izumiyama@hep.phys.titech.ac.jp"
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shotaizu/waveform-ana#readme>

dependencies:
- base >= 4.7 && < 5
- csv
- statistics
- vector
- directory >= 1.3
- bytestring-conversion >= 0.3
- binary >= 0.8
- bytestring >= 0.10

library:
  source-dirs: src

executables:
  waveform-ana-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O
    dependencies:
    - waveform-ana

tests:
  waveform-ana-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - waveform-ana
